services:
  db:
    container_name: starwars-db
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - starwars_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - starwars_network

  api:
    container_name: starwars-api
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - starwars_network

  celery_worker:
    container_name: starwars-celery
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - starwars_network

  celery_beat:
    container_name: starwars-celery-beat
    build: .
    command: celery -A core beat -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - starwars_network

volumes:
  postgres_data:

networks:
  starwars_network:
