# Generated by Django 4.2.16 on 2024-11-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=10)),
                ('eye_color', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=10)),
                ('mass', models.CharField(max_length=10)),
                ('skin_color', models.CharField(max_length=20)),
                ('homeworld', models.URLField()),
                ('species', models.JSONField()),
                ('vehicles', models.JSONField()),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('cost_in_credits', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.CharField(max_length=20)),
                ('max_atmosphering_speed', models.CharField(max_length=20)),
                ('crew', models.CharField(max_length=10)),
                ('passengers', models.CharField(max_length=10)),
                ('cargo_capacity', models.CharField(max_length=20)),
                ('consumables', models.CharField(max_length=50)),
                ('hyperdrive_rating', models.CharField(max_length=10)),
                ('MGLT', models.CharField(max_length=10)),
                ('starship_class', models.CharField(max_length=50)),
                ('pilots', models.JSONField()),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('episode_id', models.IntegerField(unique=True)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('planets', models.JSONField()),
                ('species', models.JSONField()),
                ('vehicles', models.JSONField()),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.URLField()),
                ('characters', models.ManyToManyField(related_name='films', to='api.character')),
                ('starships', models.ManyToManyField(related_name='films', to='api.starship')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='starships',
            field=models.ManyToManyField(related_name='piloted_by', to='api.starship'),
        ),
    ]
