name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest  # Ensure pylint and pytest are available

      - name: Run Pytest
        run: |
          pytest --disable-warnings
        continue-on-error: false # Fail workflow if tests fail

      - name: Run Pylint
        run: |
          pylint . --fail-under=8
        continue-on-error: false # Fail workflow if pylint score is below threshold

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: ./.pytest_cache
