name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Run pytest tests
        run: |
          pytest tests/ --disable-warnings
        continue-on-error: false

  lint:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Lint with pylint
        run: |
          pylint app/ --fail-under=8

  artifacts:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Upload Test and Lint Results
        uses: actions/upload-artifact@v3 # Updated to v3 as per the deprecation notice
        with:
          name: test-and-lint-results
          path: ./results/
